#!/bin/bash

# Create desktop dirs if they don't exist
if [ ! -d desktops ]; then
    mkdir desktops
fi

if [ ! -d desktops/work ]; then
    mkdir desktops/work
fi

if [ ! -d desktops/home ]; then
    mkdir desktops/home
fi

# TODO Byte compile:
# emacs -batch -f batch-byte-compile vendor/*.el
# ...
